name: Build Visual Studio Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MSBuild
      run: |
        # Use vswhere to find MSBuild executable path
        $msbuildPath = & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
        echo "MSBUILD_PATH=$msbuildPath" >> $GITHUB_ENV

    - name: Use MSBuild path
      run: |
        echo "MSBuild path: $env:MSBUILD_PATH"
        # Run the MSBuild command using the MSBuild path stored in the environment variable
        cmd /c "$env:MSBUILD_PATH" ArknightsMapViewer.sln /p:Configuration=Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: path/to/your/generated/files

    - name: Create Release directory
      run: |
        mkdir .Release

    - name: Copy build artifacts
      run: |
        # Copy files from the build output directory to .Release
        Copy-Item -Path .\ArknightsMapViewer\bin\Release\* -Destination .\.Release -Recurse -Force

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release-artifact
        path: .Release
