name: Build Visual Studio Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Visual Studio environment
      run: |
        $vsPath = & 'C:\ProgramData\Chocolatey\bin\vswhere.exe' -products * -requires Microsoft.Component.MSBuild -property installationPath -latest
        Write-Output "VISUAL_STUDIO_PATH=$vsPath" >> $GITHUB_ENV

    - name: Use Visual Studio path
      run: |
        echo "Visual Studio path: $VISUAL_STUDIO_PATH"
        # Ensure the environment variable is set correctly
        # Run the msbuild command
        & "$env:VISUAL_STUDIO_PATH\MSBuild\Current\Bin\MSBuild.exe" ArknightsMapViewer.sln /p:Configuration=Release /restore
