name: Build Visual Studio Project

on:
  push:
    branches:
      - main
      
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Visual Studio environment
      shell: powershell
      run: |
        $vsPath = & 'C:\ProgramData\Chocolatey\bin\vswhere.exe' -products * -requires Microsoft.Component.MSBuild -property installationPath -latest
        Write-Output "##[set-env name=VISUAL_STUDIO_PATH]$vsPath"

    - name: Build solution
      shell: powershell
      run: |
        msbuild.exe ArknightsMapViewer.sln /p:Configuration=Release
